import json
import os

# Path to the JSON file generated by calculate_weights.py
WEIGHTS_FILE = os.path.join(os.path.dirname(__file__), "ingredient_weights.json")

try:
    with open(WEIGHTS_FILE, "r") as f:
        INGREDIENT_WEIGHTS = json.load(f)
except FileNotFoundError:
    print(" ingredient_weights.json not found. Using empty weights.")
    INGREDIENT_WEIGHTS = {}
